name: Test clever cloud

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn lint
      - run: yarn test

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1
        with:
          alias: snowpact-test-app
          CLEVER_ENV_CC_POST_BUILD_HOOK: 'sh ./build.sh'
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
